name: .NET Core - Push to NuGet.Org

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Create the package
      run: dotnet pack -c Release
    - name: Publish to Nuget.org
      run: dotnet nuget push RhinoMocksToMoq/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate    
    - name: Publish to Github package
      run: dotnet nuget push RhinoMocksToMoq/bin/Release/*.nupkg -s https://nuget.pkg.github.com/minhhut/index.json -n github -u minhhut -p ${{secrets.GITHUB_TOKEN}} [--store-password-in-clear-text]
