name: .NET Core - Push to Github Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Pack
      run: dotnet pack -c Release
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push "RhinoMocksToMoq/bin/Release/*.nupkg" -s https://nuget.pkg.github.com/minhhut/index.json -k ${GITHUB_TOKEN}  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}