name: .NET Core - Push to Github

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
        source-url: https://nuget.pkg.github.com/minhhut/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create the package
      run: dotnet pack -c Release
    - name: Publish the package to GPR
      run: dotnet nuget push "RhinoMocksToMoq/bin/Release/*.nupkg"